# About you
author:
  name:           Manue
  email:          manu@false-gmail.com

# About the blog
version:          1.0.0
title:            Crossingborders
tagline:          a photo-blog adventure
description:      A description of the photo-blog adventure
paginate:         1

# URL
permalink:        pretty
url:              http://localhost:4000
# url:              http://www.crossingborders.fr
baseurl:          /
exclude:          ['Gemfile', 'Gemfile.lock']

# Paths
javascripts_path: '/public/javascripts'
stylesheets_path: '/public/stylesheets'
images_path:      '/public/images'
sass:
  sass_dir: /public/stylesheets

# Flickr vars
flickr:
  api_key:        ea1f0ff4ce1b6df0d47a12e54e26f5af

# Facebook vars
facebook:
  app_id:         702447933160068

# Dependencies
markdown:         rdiscount
gems:
  - jemoji
  - jekyll-sitemap

# Prose
prose:
  rooturl: '_posts'
  siteurl: 'http://mpepito13.github.io/'
  relativeLinks: 'http://mpepito13.github.io/links.jsonp'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "latitude"
        field:
          element: "number"
          label: "Latitude"
          value: ""
      - name: "longitude"
        field:
          element: "number"
          label: "Longitude"
          help: "Give me coordinates so I can place a marker on the map."
          value: ""
      - name: "country"
        field:
          element: "text"
          label: "Country"
          help: "Give me coordinates so I can place a marker on the map."
          value: ""
      - name: "bouton"
        field:
          element: "button"
          label: "Tst button"
          on: "Je suis on"
          off: "Je suis off"
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
