# About you
author:
  name:           Manue
  email:          manu@false-gmail.com

# About the blog
version:          1.0.0
title:            Crossingborders
tagline:          a photo-blog adventure
description:      A description of the photo-blog adventure
paginate:         1

# URL
permalink:        pretty
url:              http://localhost:4000
# url:              http://www.crossingborders.fr
baseurl:          /
exclude:          ['Gemfile', 'Gemfile.lock']

# Paths
javascripts_path: '/public/javascripts'
stylesheets_path: '/public/stylesheets'
images_path:      '/public/images'
sass:
  sass_dir: /public/stylesheets

# FlickRaw vars
flickr:
  api_key:         ea1f0ff4ce1b6df0d47a12e54e26f5af

# Dependencies
markdown:         redcarpet
gems:
  - jemoji
  - jekyll-sitemap
